name: react_grid_view
description: React Grid View.
version: 0.0.1
author: "Hyeonki Hong<hhk7734@gmail.com>"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  json_annotation: ^3.1.1
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.12
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true
